### ISSUE TITLE
Carbon ->diffForHumans() issue

### ISSUE THREAD

**Issue by vonec** [DarkGhostHunter/Laraload#18]
Argument 1 passed to Carbon\\CarbonInterval::setLocalTranslator() must be an instance of Symfony\\Component\\Translation\\TranslatorInterface, instance of Carbon\\Translator given, called in /var/www/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php on line 778"

getting this only when using preload, can you suggest me what's going wrong on this

Few features that could be useful:
1. CountRequests hits could be configurable
2. Counter on cache should reset to zero after generation

**Comment by vonec** [comment]
issue got fixed after changing to
    'memory' => 64,

**Comment by vonec** [comment]
https://github.com/DarkGhostHunter/Laraload/pull/19 hope this get merged

**Comment by DarkGhostHunter** [comment]
ARSadshdjawgauysgdajhdbasd... okay, okay... I'll add both on the next version.

**Comment by DarkGhostHunter** [comment]
On a sidenote, only the reset to zero. The hits is easily configurable via Container. I'll add the latter into the readme.
