### ISSUE TITLE
Command or initial preload.php file

### ISSUE THREAD

**Issue by fridzema** [DarkGhostHunter/Laraload#2]
Hello, 
How are you supposed to start with this package? If i point my opcache settings to preload.php it doesn't exists and trows an 502 error.

**Comment by DarkGhostHunter** [comment]
Use the preloader to generate the script. Once generated, point PHP to load the file, not before.

Please read the documentation.

I added some aclaration for the matter:

https://github.com/DarkGhostHunter/Laraload/blob/master/README.md#what-is-preloading-what-does-this
