### ISSUE TITLE
Add Laravel 8 support

### ISSUE THREAD

**Issue by theanadimukt** [DarkGhostHunter/Laraload#22]

**Comment by d8vjork** [comment]
Added on commit 74b5548965da9d653a9c2da50270d8aef56b36c9

Waiting for release 👀  @DarkGhostHunter

**Comment by danilopolani** [comment]
+1 for the release. Currently I required the package with `composer require --dev darkghosthunter/laraload:dev-master` to let it fetch the `master` branch with L8 support. Not the safest way, but I added it only as dev dependency so it's kinda safe

**Comment by nyrik8989** [comment]
+1

**Comment by daverdalas** [comment]
@DarkGhostHunter any update on it?

**Comment by DarkGhostHunter** [comment]
Updated. Landing in an hour.
