### ISSUE TITLE
How can I disable Laraload?

### ISSUE THREAD

**Issue by vladrusu** [DarkGhostHunter/Laraload#28]
Hi there!

If I comment out ;opcache.preload in php.ini, the preload.php file is still generated every 500 requests (of course).
Is there a way to temporarily disable the middleware/plugin ?
Say, a disable=true flag in config/laraload.php ?

Also, it would be nice that on the first run to generate the storage/preload.php file in LESS than 500 requests (for local testing), if the file doesn't exist.
I had to hit refresh dozen of times until the file was generated, this is less than ideal...

Thanks!

**Comment by DarkGhostHunter** [comment]
Nope, it can't be disabled.

I could add a switch on the config on the next patch version, unless you beat me to it.

**Comment by DarkGhostHunter** [comment]
I added it. Coming in the next patch.

**Comment by vladrusu** [comment]
Thanks !

How about the second thing I asked? Do you think is doable?

> Also, it would be nice that on the first run to generate the storage/preload.php file in LESS than 500 requests (for local testing), if the file doesn't exist.
> I had to hit refresh dozen of times until the file was generated, this is less than ideal...

**Comment by DarkGhostHunter** [comment]
Check a t the end of the readme. 

Italo Baeza C.

**Comment by DarkGhostHunter** [comment]
https://github.com/DarkGhostHunter/Laraload/releases/tag/v2.3.0
