### ISSUE TITLE
502 Error after settting path to preload.php and restarting PHP

### ISSUE THREAD

**Issue by ArjenNZ** [DarkGhostHunter/Laraload#31]
Hi there,

Thanks for creating this wonderful package.

Im only running into a problem while updating the PHP FPM file in Laravel Forge.

I'm setting `opcache.preload = '/home/forge/mysite.com/storage/preload.php'` (as the path when typing pwd).

preload.php also exists. Double checked that.

But upon reloading PHP nginx logs the following error:

`[crit] 5395#5395: *85 connect() to unix:/var/run/php/php7.4-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 213.127.61.8, server: mysite.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "mysite.com"`

Which may be due to the fact that pfm-php can't find /home/forge/mysite.com/storage/preload.php?

Any idea how to fix this issue?

Best regards!

**Comment by DarkGhostHunter** [comment]
> Which may be due to the fact that pfm-php can't find /home/forge/mysite.com/storage/preload.php?

PHP Socket can't be found. Check your PHP logs, it may be something else.

**Comment by ArjenNZ** [comment]
I found the errors in the syslog. I had to uncomment the preload_user and set it to forge.
