### ISSUE TITLE
syntax error, unexpected 'App' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 

### ISSUE THREAD

**Issue by coding-sunshine** [DarkGhostHunter/Laraload#5]
Getting this error on the new installation

Also on another error when I try to fix the above.

Please see the 
<img width="1303" alt="Screen Shot 2020-02-12 at 3 40 22 pm" src="https://user-images.githubusercontent.com/3206025/74303479-221a0400-4dae-11ea-9466-a3558c8c9a23.png">
<img width="1361" alt="Screen Shot 2020-02-12 at 3 40 41 pm" src="https://user-images.githubusercontent.com/3206025/74303481-26462180-4dae-11ea-8c03-66bfbc1a34db.png">

screenshot.

**Comment by coding-sunshine** [comment]
Also just to confirm the preload.php is not being generated on my storage path even if I try to fix above :(

**Comment by DarkGhostHunter** [comment]
That error pops out when you're not running PHP 7.4.

Explanation: Typed properties are part of PHP 7.4. Lower versions will mistake the type as a function name or a constant, and since it's neither of those, an error will be thrown.
