### ISSUE TITLE
got error after set opcache.preload

### ISSUE THREAD

**Issue by cron13** [DarkGhostHunter/Laraload#7]
Hi, i use laravel 6.16.0 with nginx+apache+php-fpm 7.4.2
After i set opcache.preload i got error
`Too few arguments to function Swift_Transport_EsmtpTransport::__construct(), 0 passed in /var/www/evg_megalid/data/www/megalid.ru/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SmtpTransport.php on line 35 and at least 3 expected
`
here is my preload.php
[preload.php.zip](https://github.com/DarkGhostHunter/Laraload/files/4224987/preload.php.zip)

**Comment by DarkGhostHunter** [comment]
Do you have the full stack trace? Seems something in your code tried to call it wrongly.

Also, you may want to change from require to compile if execution of the preloader script gives you trouble (I'm on mobile and I can't see your zip).

**Comment by tm1000** [comment]
Same issue in Laravel 8. I think swiftmailer has issues being preloaded.

Easy Fix:
In AppServiceProvider.php => boot()
```php
        Laraload::exclude(function (Finder $find) {
            $find
                ->in(base_path() . '/vendor/swiftmailer')
                ->name('*.php');
        });
```

This is probably resolved in the symfony maintained version of swift (which is now called mailer)
