### ISSUE TITLE
error: This package requires php 7.4 but your PHP version (7.4.3) does not satisfy that requirement.

### ISSUE THREAD

**Issue by ibrunotome** [DarkGhostHunter/Laraload#8]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php 7.4 but your PHP version (7.4.3) does not satisfy that requirement.

**Comment by DarkGhostHunter** [comment]
Seems weird, considering the [composer.json](https://github.com/DarkGhostHunter/Laraload/blob/master/composer.json#L19) points to the correct version.

```json
"require": {
        "php": "^7.4",
        "illuminate/support": "6.*",
        "illuminate/contracts": "6.*",
        "darkghosthunter/preloader": "^1.1.3"
    },
```

I'll try to replicate that myself once I come back to working duties.

**Comment by ibrunotome** [comment]
Remove .lock and generated it again solved the error. Thanks.
